# Generated by Django 3.2.10 on 2022-04-10 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beat',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='beat',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beat',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
