# Generated by Django 3.2.10 on 2022-05-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
