# Generated by Django 4.0 on 2021-12-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0002_beat_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beat',
            old_name='coordinates',
            new_name='route',
        ),
    ]
