# Generated by Django 3.2.10 on 2022-06-05 15:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0002_beat_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='polygon_buffer',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
