# Generated by Django 3.2.10 on 2022-06-05 16:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0003_beat_polygon_buffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='polygon_buffer',
        ),
        migrations.AddField(
            model_name='beat',
            name='start_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
