# Generated by Django 4.0 on 2021-12-21 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0003_rename_coordinates_beat_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 21, 21, 16, 8, 617390)),
            preserve_default=False,
        ),
    ]
