# Generated by Django 3.2.10 on 2022-07-07 20:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0004_auto_20220605_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='private',
            field=models.BooleanField(default=False, help_text='Route is private'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='route',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, help_text='Route data', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='beat',
            name='start_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='start geo location of the route', null=True, srid=4326),
        ),
    ]
