# Generated by Django 3.2.10 on 2021-12-29 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0001_postgis_extention'),
        ('beats', '0005_beat_user'),
    ]

    operations = [
    ]
