# Generated by Django 3.2.10 on 2022-04-10 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0002_auto_20220410_1900'),
        ('common', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='beat',
            field=models.ForeignKey(blank=True, help_text='Comment on Beat', null=True, on_delete=django.db.models.deletion.CASCADE, to='beats.beat'),
        ),
        migrations.AlterField(
            model_name='like',
            name='beat',
            field=models.ForeignKey(blank=True, help_text='Kudos given to Beat', null=True, on_delete=django.db.models.deletion.CASCADE, to='beats.beat'),
        ),
    ]
