# Generated by Django 3.2.10 on 2022-04-10 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0001_initial'),
        ('beats', '0002_auto_20220410_1900'),
        ('common', '0003_auto_20220410_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(max_length=500, upload_to='uploads/')),
                ('description', models.TextField(blank=True, null=True)),
                ('beat', models.ForeignKey(blank=True, help_text='Kudos given to Beat', null=True, on_delete=django.db.models.deletion.CASCADE, to='beats.beat')),
                ('problem', models.ForeignKey(blank=True, help_text='Kudos given to Beat', null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
