# Generated by Django 3.2.10 on 2022-06-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_following'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='following',
            constraint=models.UniqueConstraint(fields=('user', 'recipient'), name='user_recipient_constraint'),
        ),
    ]
