# Generated by Django 3.2.10 on 2022-04-21 20:59

import TM470_backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, storage=TM470_backend.storage_backends.PrivateMediaStorage, upload_to='images/users/'),
        ),
    ]
